name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read node-version from .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}" # see previous run-statement

      - run: npm install
      - run: npm test
      - run: npm start
